version: "3.8"
services:
  dev:
    stdin_open: true
    tty: true
    container_name: open-music-player-dev-server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"
    - "6006:6006"
    volumes:
    - ".:/app"
    - "/app/node_modules"
    - "/app/.husky"
    environment:
      CHOKIDAR_USEPOLLING: "true"
